formatter_format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
log_path = '/Workspace/Users/prasanthiyyappan@gmail.com/fraud_detection_w_delta_lake/logs/'
bad_records_path= 's3a://prasanth-s3bucket-ver1/fraud_detection_data/bad_records/bronze'
check_point_path = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/checkpoints/bronze'
bronze_write_path = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/delta/bronze'
stream_file = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/stream_ingestion/'
bronze_dq_result_folder = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/data_quality/bronze'
silver_dq_result_folder = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/data_quality/silver'
lkp_ip_risk = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/lookup_data/ip_risk_levels_nvidia.csv'
lkp_prod_list = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/lookup_data/products_nvidia.csv'
lkp_subs_plan = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/lookup_data/subscription_plans_nvidia.csv'
lkp_users = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/lookup_data/users_nvidia.csv'
format_patterns = {"ip_address": r"^\d{1,3}(\.\d{1,3}){3}$",
    "card_number": r"^\d{12,19}$",
    "currency": r"^[A-Z]{3}$"}
silver_read_path = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/delta/bronze'
silver_write_path = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/delta/silver'
silver_check_point_path = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/checkpoints/silver'
gold_read_path = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/delta/silver'
gold_write_path_spend_summary = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/delta/gold/user_spend_summary'
gold_write_path_product_usage_metrics = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/delta/gold/product_usage_metrics'
gold_write_path_high_risk_txns = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/delta/gold/high_risk_txns'
pii_path = 's3a://prasanth-s3bucket-ver1/fraud_detection_data/delta/pii'